### ISSUE TITLE
KVTree release for SCR v3.0rc1

### ISSUE THREAD

**Issue by gonsie** [ECP-VeloC/KVTree#49]
See SCR v3.0 project: https://github.com/llnl/scr/projects/2

## Process

- [x] Merge any existing PRs
- [x] Create a commit(s) which updates the project version number in the code and updates references to any dependency versions.  
- [x] Merge the commit
- [x] Tag a release on GitHub
- [x] Add release note (can be done after the release is tagged)
- [x] Update the spack package, both with the version hash and the dependency versions.

**Comment by gonsie** [comment]
@adammoody @CamStan I see that #51 should get merged before a release. Is there anything else? 

On the [SCR v3.0 project board](https://github.com/LLNL/scr/projects/2) there is a reference to the KVTREE_LOCK_FILE, was that something for KVTree, or for the spack package?

**Comment by CamStan** [comment]
Nope, I haven't run into anything else, so for me that's it for this one.

The `KVTREE_LOCK_FILE` reference is for the spack package. I've already added it and will push it to spack once I can add the new KVTree release as well.

**Comment by CamStan** [comment]
@adammoody, @gonsie, I just noticed this card on the project page: https://github.com/LLNL/scr/projects/2#card-57453917.

I recently updated Travis CI for UnifyFS to build with newer compilers, so shouldn't take much work to update the components. 
If we want to test on the newer compilers and clean up build errors before tagging releases, we might want to wait on merging #52 and I can start focusing on this.

**Comment by adammoody** [comment]
@CamStan , oh yeah, that could help.  I was figuring we could do it by hand if nothing else, but having this included in the testing could be better.

I always think it's ugly and worrisome when I build a project that spews a bunch of compile warnings.  But more importantly, I've found that ~30-50% of compiler warnings point to legitimate code bugs, so it's an easy way to find and fix bugs before stamping a release.

**Comment by adammoody** [comment]
@CamStan , given that the code teams need a release sooner rather than later, I'm thinking we should aim for a follow up release.  We could make a 3.0rc1 in a couple weeks and then a 3.0 proper perhaps a month later so that we can clean up loose ends.  And with that, let's push the compiler warning item to the 3.0 to come later.

**Comment by CamStan** [comment]
> let's push the compiler warning item to the 3.0 to come later.

Sounds good. We can go ahead and merge #52 then.

**Comment by CamStan** [comment]
Spack package PR: https://github.com/spack/spack/pull/22852
